### ISSUE TITLE
[Bug]: Patchouli Book is Invalid

### ISSUE THREAD

**Issue by CassieRoseZA** [MattiDragon/ExtendedDrawers#72]
### Description of the issue

Patchouli Book is Invalid
![image](https://github.com/MattiDragon/ExtendedDrawers/assets/13422754/8c67f1f9-2da2-4216-a7bc-f93893c733a7)

### Reproduction steps

1. load the mod with patchouli & REI
2. Lookup @patchouli 
3. See it shows invalid book

### Mod version

2.0.3+mc.1.20.1

### Operating System

Win 10

### Minecraft version

1.20.1

### Other mods

Fabric API v0.85.0+1.20.1
Roughly Enough Items v12.0.630

### Server

Happens

### Client

Happens

### Logs

[12:59:56] [Render thread/ERROR]: Failed to load book extended_drawers:guide defined by mod extended_drawers, skipping
java.lang.IllegalArgumentException: Book extended_drawers:guide has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

**Comment by MattiDragon** [comment]
I haven't updated the patchouli support to 1.20 yet as patchouli wasn't released for 1.20 when I last checked.

**Comment by CassieRoseZA** [comment]
it was updated on the 9th

**Comment by MattiDragon** [comment]
And last I checked was probably around two weeks ago. I'll fix it
